//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.PatientReportModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TreatemntID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Prescription { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
